version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - backend-data:/app  # named volume (on remote host) or bind mount
    ports:
      - "8000:8000"
    environment:
      - VITE_SERVER_DOMAIN=http://192.168.1.5:8000
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - frontend-data:/app  # named volume (on remote host) or bind mount
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend-data:
  frontend-data: